### ISSUE TITLE
Hyperlink from Collections to Phenotypes page bug

### ISSUE THREAD

**Issue by alexcoldea** [SwanseaUniversityMedical/concept-library#1071]
Steps to reproduce: 
- Search a phenotype on the demo site (e.g Al1 All anomalies). Don't clear the content in the search bar.
- Select HDRUK website version
- Go to Collections -> BREATHE and click on the hyperlink "Browse BREATHE Phenotypes". 

Any previous content should be cleared from the search bar and only BREATHE phenotypes should be displayed.

**Comment by Hannah-Davies** [comment]
check if still exists with the recent changes
