### ISSUE TITLE
Discrepancy in module usage

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1112]
# Issue
Not all new code is utilising the newer entity methods e.g. reliance on prev. `constants.py` and `Permissions.py`. 

Legacy modules will be removed once we have fully committed to the new design, and there are some differences in the handling of permissions & constant values - needs urgent attention for those that have used the legacy modules.

# To resolve
New code should be using the newer permission & constants module, as well as the new entity utility methods found within `clinicalcode/entity_utils`

# Tasks
- [x] Fix dependency usage
- [x] Fix sub-dependencies due to #1348

**Comment by JackScanlon** [comment]
Need to sort this out - we have duplicated functions inside entity utils - is `entity_db_utils` required?

**Comment by elmessary** [comment]
Yes, please leave `entity_db_utils`.
I'll look further into newer permission & constants
