### ISSUE TITLE
Look at design for History / version control

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1115]
Clean up publish tables

Have publication status in main phenotype table
log moderations history of actions in a separate table

Will help with query code

- [ ] Agree data model (version v status)
[ ] keep current functionality - save gives new version and then look at how we improve on that.
[ ] how does draft status work as not everyone wants to go from draft straigt to publish
[ ] what actions to log on review - move publication status to main phentype table
[ ] how will work with permissions (unpublished phenotypes only -move permissions to a separate table with no history , behave like GIT repo permissions
- Concept has phenotype ID and like to permisions table to get permissions for concept

- [ ] migrate data
- [ ]

**Comment by JackScanlon** [comment]
- [x] Create document to discuss changes required to meet criteria as described above
- [ ] Awaiting meeting to progress

**Comment by JackScanlon** [comment]
## Closure
Closed as:
- Associated with #1091
- Team decided not to go ahead with changes
