### ISSUE TITLE
Update page designs - About pages

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1144]
# Issue
Now that the search, my collection, detail and create/update pages are utilising the new design, we need to update the rest of the pages to align with the current UI/UX.

# Linked tasks
- Per #1120
  - @ZinnurovArtur: _"We need to agree on which data should we display on the About page. Potentially new model designs"_

- About page tasks
    - #322
    - #1120 

- Misc. design changes tasks
    - Brand-based favicon for tabs →  #660
    - Layout → #398

**Comment by ieuans** [comment]
Closed, finished in #1247
