### ISSUE TITLE
Update page designs - Contact us page

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1145]
# Issue
Now that the search, my collection, detail and create/update pages are utilising the new design, we need to update the rest of the pages to align with the current UI/UX.

# Related / Conflicting issues
- '_New Content_' page partially relates / conflicts with #1108
    - I imagine we will want admins/moderators/non-technical staff to be able to update/create content for this page
    - Development on this prior to finalising UAM will result in duplication of work

# Linked tasks
1. Misc. design changes
    - Brand-based favicon for tabs →  #660
    - Layout → #398

**Comment by ieuans** [comment]
Closed, finished in #1246
