### ISSUE TITLE
dropdown-btn issue if more than one added to the page

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#1221]
in detail page we have 2 dropdown-btn
if I click one of them it works directly (after 1 click) but the other takes 2 clicks to work
and vise versa.

**Comment by JackScanlon** [comment]
Can use the `dropdown-selection` class which will achieve the same behaviour as being able to click to different items? If not, may be better to use a different component, or even use the `<select/>` tag dependent on what behaviour you want?

The `dropdown-btn` class behaves like this intentionally as it does not use JS to drive its interactions. Internally it relies upon CSS rules and radiobuttons to determine which state its in, so when opened, the screen's input is sunk to the dropdown buttons and the surrounding areas to allow the dropdown to close.

If you use the `dropdown-selection` class, which can be seen on the `/search/` page, it will behave in the way that you describe but relies upon JS to manage its interactions - code for that can be found within `/redesign/components/dropdown.js`
