### ISSUE TITLE
Export methods for CSV/XML etc use server compute instead of leveraging client

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1222]
# Issue
Our export methods for non-API views use server methods to generate CSV/XML data for export, specifically `export_entity_codes_to_csv` method within _'../views/GenericEntity.py'_

The codelist and its associated codes, used by the export methods as params, are already sent in the context to the views to be rendered via HTML - we should create these files on the client instead of using valuable server compute time

Codelists can contain large amounts of data, iterating over every code on the server for something that can be achieved on client is both computationally expensive and eats into our compute time / resources

# Assignee
Whoever created / utilises the `export_entity_codes_to_csv` method should take a look at moving this functionality over to the client

**Comment by elmessary** [comment]
- This is low priority atm.
- Since the output should be the same as the one from the API endpoints,
 it would be difficult to maintain two pieces of code to produce the same output
