### ISSUE TITLE
Cookie alert banner functionality

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1225]
# Issue
Observations about the banner:

1. The _'Customise Settings'_ button closes the banner without opening up a menu interface to alter settings
2. It relies on bootstrap and jQuery - neither are included in the base HTML page by default, if they're required to function, we need to look at this

# Question
Do the cookie settings actually function correctly? Looking at the code, it doesn't seem to be functional - this is less important for now because we haven't implemented analytics but we need to examine and fix this ASAP if we intend to impl. analytics

**Comment by ZinnurovArtur** [comment]
This cookie alert was created during bootstrap 3. And customise settings and other functionalities is working differently depends on version of website(demo,prod,read-only). The full functionality of the cookie banner works only in the production. I can redisign this for the new version
