### ISSUE TITLE
Discrepancy in CSV export of codelists

### ISSUE THREAD

**Issue by JackScanlon** [SwanseaUniversityMedical/concept-library#1267]
# Issue
### Discrepancy in columns and their data
In some code lists, the exported CSV file takes the shape of:

| Code | Description | ... | Attribute 1 | Attribute 2 |
|------|-------------|-----|-------------|-------------|
| U071 | ...         | ... | VALUE       | VALUE       |
| U072 | ...         | ... | VALUE       | VALUE       |
| U0.. | ...         | ... | VALUE       | VALUE       |

In others, however, the exported CSV contains a dictionary for the attributes of each code, e.g.

| Code | Description | ... | code_attributes |
|------|-------------|-----|-----------------|
| U071 | ...         | ... | {'type': 1}     |
| U072 | ...         | ... | {'type': 1}     |
| U0.. | ...         | ... | {'type': 1}     |

This is an issue for a few reasons:
1. No consistent format for data manipulation & analysis as is intended with these export methods
2. Parsing the `code_attributes` column wouldn't be pleasant (as described below)

### Issue with parsing
The `code_attributes` columns in the example above, and any code lists that follow this pattern, all use Python's dictionary format and thus, aren't able to parsed as JSON.

If this was intended, the values should at least be _stringified_ as JSON so they can be manipulated by the downloaders.

**Comment by elmessary** [comment]
This was an old situation.
but I agree on having the same output like the 2nd example and stringify json.
Thanks
