### ISSUE TITLE
Typo in CKD phenotype: 

### ISSUE THREAD

**Issue by spiros** [SwanseaUniversityMedical/concept-library#1330]
https://phenotypes.healthdatagateway.org/phenotypes/PH42/version/1527/detail/

Current text:
“Where egfr_ckdepi up to and including 31 Dec 2013 is defined as: egfr_ckdepi = 141 * min(crea_gprd * 0.010746 / K, 1)^alpha * max(crea_gprd * 0.010746 / K, 1)^-1.209 * 0.993^age * 1.018 [if female] * 1.159 [if black]
where: alpha = -0.329 for females, -0.411 for males K = 0.7 for females, 0.9 for males
Where egfr_ckdepi from and including 1 Jan 2014 is defined as: egfr_ckdepi = 141 * min(crea_gprd * **_0.010746_** / K, 1)^alpha * max(crea_gprd * **_0.0.011312_**/ K, 1)^-1.209 * 0.993^age * 1.018 [if female] * 1.159 [if black]
where: alpha = -0.329 for females, -0.411 for males K = 0.7 for females, 0.9 for males”

Please amend to:
“Where egfr_ckdepi up to and including 31 Dec 2013 is defined as: egfr_ckdepi = 141 * min(crea_gprd * 0.010746 / K, 1)^alpha * max(crea_gprd * 0.010746 / K, 1)^-1.209 * 0.993^age * 1.018 [if female] * 1.159 [if black]
where: alpha = -0.329 for females, -0.411 for males K = 0.7 for females, 0.9 for males
Where egfr_ckdepi from and including 1 Jan 2014 is defined as: egfr_ckdepi = 141 * min(crea_gprd ***_0.011312_**/ K, 1)^alpha * max(crea_gprd * **_0.011312_**/ K, 1)^-1.209 * 0.993^age * 1.018 [if female] * 1.159 [if black]
where: alpha = -0.329 for females, -0.411 for males K = 0.7 for females, 0.9 for males”

**Comment by elmessary** [comment]
@spiros 
so both corrections will use 0.011312?

**Comment by spiros** [comment]
> @spiros so both corrections will use 0.011312?

Yep!
