### ISSUE TITLE
SAIL Sensitive Codes Concepts have disappeared

### ISSUE THREAD

**Issue by DSThayer** [SwanseaUniversityMedical/concept-library#1433]
Hi, 

We had several concepts related to sensitive codes in SAIL. They were not published but accessible to all logged-in users (and important for SAIL users to access). 

What has happened to them? I can't find them on the Library.

**Comment by DSThayer** [comment]
I don't know whether this is related to orphaned concepts not being visible because they are not within a phenotype; or a permissions issue.

**Comment by elmessary** [comment]
It was found :)
