### ISSUE TITLE
Define a set of automated functional tests

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1460]
Need to define what functional tests need to be automated
eg Tests around phenotype templates - having 2 or more templates
tests around managing the version of templates
ability to migrate to different versions of templates

**Comment by roshantoby** [comment]
[test to check new version for template.xlsx](https://github.com/SwanseaUniversityMedical/concept-library/files/13557789/test.to.check.new.version.for.template.xlsx)

**Comment by roshantoby** [comment]
[test to check new version for template.xlsx](https://github.com/SwanseaUniversityMedical/concept-library/files/13559673/test.to.check.new.version.for.template.xlsx)

**Comment by roshantoby** [comment]
[test_cases.xlsx](https://github.com/SwanseaUniversityMedical/concept-library/files/14277808/test_cases.xlsx)

**Comment by Hannah-Davies** [comment]
https://docs.google.com/spreadsheets/d/1fdVDEWkWofYIx_djrSRcf4-eM4h0rPitUehu_dpaA9c/edit#gid=0
