### ISSUE TITLE
Create function to set environment variables 

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1473]
Comment from Marcos following time out issue https://github.com/SwanseaUniversityMedical/ConceptLibraryClient/issues/9

It'll be great if the concept library had a function like `set_environment_variables("Win")` to help with this. You can then catch the exception and rise a message recommending/reminding the user to run such function.

# Tasks
- [x] Impl. setter on `DOMAINS$GATEWAY`

**Comment by ieuans** [comment]
This is already planned but I wanted to talk to the tech team first since these variables should be set automatically. It affects other environment variables too, e.g. IBM_DB_HOME, where sometimes on monthly gateway shutdowns not all variables are set on rebooting the VMs
