### ISSUE TITLE
Adjust pipeline github documentation to keep files

### ISSUE THREAD

**Issue by ZinnurovArtur** [SwanseaUniversityMedical/concept-library#1477]
Currently, the testing pipeline generates the allure report on the GitHub pages branch, however, GitHub docs use the same GitHub pages branch. The GitHub docs pipeline needs to be adjusted so it is not delete the original files from Allure

**Comment by alexcoldea** [comment]
- The Documentation generation push on github pages overrides the content on Github-pages.
- Github-pages branch to be used for documentation only.
- Next steps are looking into allure-reports test generation deployment with netlify.

**Comment by Hannah-Davies** [comment]
@alexcoldea to revert changes
