### ISSUE TITLE
Add licencing statement to library

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1485]
need to add a licencing statement or T&C about how the photypes nad their content can be used.

Add information regarding copywrite re codes eg WHO for ICD10

**Comment by Hannah-Davies** [comment]
need to agree where to place this

**Comment by DSThayer** [comment]
@ieuans here is a suggested modification to the copyright statement on the footer:

> Copyright © 2024 - SAIL Databank - Swansea University. User-submitted content held in the Library is openly licensed for non-commercial use via [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). All other rights reserved.

And in the Ts&Cs, likewise add a bullet point under "Uses of content". 

> User-submitted content held in the Library is openly licensed for non-commercial use via [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
