### ISSUE TITLE
Pharmacological Phenotypes - UK Biobank - review response from Spiros for way forward

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1500]
Once we have the clarification for questions we have asked we will need to work out what is required to move forward with next phase for loading data

Linked to #1547

**Comment by DSThayer** [comment]
I have told them we are ready to receive the full collection of phenotypes; waiting on them.

They want the phenotypes to be embargoed until they publish a paper, so can be loaded but not published.

**Comment by DSThayer** [comment]
This is complete, and we are awaiting all phenotypes to load them.
