### ISSUE TITLE
API/Search/Detail Authentication & Access to Phenos Functional Tests

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1545]
pick up and write some scripts from the functional test list
https://docs.google.com/spreadsheets/d/1fdVDEWkWofYIx_djrSRcf4-eM4h0rPitUehu_dpaA9c/edit#gid=0

**Comment by alexcoldea** [comment]
**Auth tests:**
- API/Search/Detail: Authenticated user can view unpublished phenotype/concept with group, owner or world_access.view (completed & testing)
- API/Search/Detail: Authenticated user cannot view an unpublished phenotype/concept without group access or world_access.view (in progress)
- API/Search/Detail: Non-authenticated user can view published phenotype/concept (in progress)
