### ISSUE TITLE
Design Analytics functionality

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1546]
Following on from #1498 and the meeting held, the design for how we deal with analytics needs to be written up.
Notes from the meeting:
a) We want to measure adoption and use of the library.  Web analytics not a good reflection of use.  How do we capture real usage of the library
b) Things to track over a period -
*API usage
*number of new phenotypes created
*number of phenotype edits
*number of unique users logged in
*number phenotypes published
*number downloads of code lists
c) being able to track by brand will be useful for futureproofing
d) Log results in a table that will allow us to query the data in any way we feel is necessary
e) Need to recognise the limitation to unique users when considering the public page where they have not logged in
*track authenticated APIs
*count non authenticated APIS
f)  How to distinguish use of robots
g)  Potentially look at associating users with brands.
need to look at enquiry form so that it tracks from which brand the request comes from

Points added after design review

h) Log user user searches for phenotypes.

**Comment by roshantoby** [comment]
![image](https://github.com/SwanseaUniversityMedical/concept-library/assets/127117890/385728df-ea4f-4511-8e58-75909b7a2f06)

Questions stills to be answered: how to detect if visitor is a robot?
