### ISSUE TITLE
working sets - 1. Adding new components (buttons, adjust tables)

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1562]
Sub set of work required to meet issue #1559

**Comment by ZinnurovArtur** [comment]
- [X] Modal for attribute creation
- [X]  Inputs for the modal
- [X] Basic button
- [ ]  Styles for button
- [ ] Initial test table with attribute

**Comment by Hannah-Davies** [comment]
remaining items now covered in the issues linked above.  Closing this task
