### ISSUE TITLE
Blog: review 2 proposed packages more in depth

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1682]

**Comment by nayim7868** [comment]
Block package choice documentation

For the Concept Library website codebase, Django CMS with Blog is the optimal choice. It allows for smooth integration with the existing Django project setup, offers various features for a customizable blog page, and has strong community support and documentation.

Seamless Integration
Smooth Integration: Django CMS works smoothly with our existing Django setup, allowing us to use our current knowledge and codebase without major changes.
Unified Admin Interface: Using the familiar Django admin panel keeps content management straightforward and consistent for content managers.

Customizability and Features
Features: Django CMS includes many features for building a customizable blog page, such as plugins, placeholders, version control, tags, categories, comments, and multimedia support.
Flexibility: Its modular design lets us extend and customize blog functionality as needed.

Strong Community Support
Active Community: Django CMS has a community that regularly updates and improves the platform, ensuring it stays secure and up-to-date.
Documentation: Detailed documentation makes setup, customization, and maintenance straightforward, reducing the learning curve and speeding up development.

Familiar Environment
Developer Convenience: Sticking with a Django-based solution means our development team can work within a familiar environment, using existing skills and avoiding extensive retraining.
Consistent Workflow: Using the same admin interface for both Django and Django CMS simplifies content management and keeps workflows consistent for our team.

------------------------

Wagtail offers the StreamField feature, making it highly customizable, user-friendly, and powerful if the goal is to have a flexible content creation system. However, it has slightly more challenges compared to Django CMS Blog. The admin interface differs from the standard Django admin, which would require learning the new interface. Wagtail also requires understanding Wagtail-specific models and page setup. The learning curve for Wagtail-specific models and StreamField adds complexity that might not be necessary for our needs. It also may demand changes in the existing setup.
