### ISSUE TITLE
Redesign - Should component have a name that is understandable

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#362]
Carried over from #349 

should the component have a set name that is understandable? currently have format of kuan_AAA_NJ2gf6ZTTxjayMcK5ksHXf_Read2 (Abdominal aortic aneurysm - concept_root - Primary care Read code)

Not required for R1 but need to look at standard for future - is it a mandatory field etc

**Comment by JackScanlon** [comment]
Closed as completed since sensible names are encouraged by new interface through regex pattern
