### ISSUE TITLE
concept names are duplicated - under same phenotype- when scrapped from the same tab

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#367]
if the same table has 2 coding systems
the 2 concepts have exactly the same name
like
'Fatty Liver - concept_root - Primary care'
in
'Fatty Liver' phenotype
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH5243/version/20855/detail/

I think adding the coding system name to the concept name will solve this, if possible

**Comment by ieuans** [comment]
Non-issue in latest version
