### ISSUE TITLE
Support export of phenotype content/use of API

### ISSUE THREAD

**Issue by DSThayer** [SwanseaUniversityMedical/concept-library#377]
The current export button only exports a table of clinical codes. It would be helpful to support the user in exporting all content and/or using the API to get all content.

Some ideas for v2:

- Perhaps the "export" that only gets the clinical code table should be moved down to the clinical code section
- Export at the top of type JSON or XML exports the entire phenotype content, not just codes.
- A phenotype page could display the API call required to access that phenotype, and even the R code that uses the package to access that phenotype.

**Comment by elmessary** [comment]
use versioned links
/api/v1/phenotypes/{id}/version/{version_id}/detail/

**Comment by elmessary** [comment]
all done
except the R code that uses the package to access that phenotype.


will create an issue for this.
