### ISSUE TITLE
Amend display order of APIs on API page - public 1st

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#471]
I think we should 1) list the public APIs first; and 2) put the ones that require authentication second under a separate heading "Authenticated APIs" with a comment that they need a user account.

**Comment by Hannah-Davies** [comment]
Wording:
Authenticated APIs return both public content and content that has not yet been published. A user account is required.

**Comment by ChrisGreenSU** [comment]
Pull request raised #472 to fix issue and update the page.
