### ISSUE TITLE
replace the special characters used in brand/HDRUK html files

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#481]
many of the HDRUK about pages contain special characters e.g to do quotation like shown in image,
this prevents saving the file with the project encoding as shown.

Need to replace all occurrences of those special characters (in brand/HDRUK all html files) with proper characters under cp1252

![special-char](https://user-images.githubusercontent.com/33552352/140985665-256f6def-53ef-4848-8cca-883dbc4212c0.png)

**Comment by Hannah-Davies** [comment]
completed
