### ISSUE TITLE
upload new additional Uni of Manchester phenotypes

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#482]

**Comment by shahzadmumtaz22** [comment]
Hi Hannah, 

I have not got a chance to update on this as got some urgent things to do over the last few days. The remaining phenotypes of UoM are processed and needs to do tests before sharing with Ieuan to upload on the library.

**Comment by shahzadmumtaz22** [comment]
Hi Hannah, 

I have created a github subfolder ([Extract2_MorePhenotypes](https://github.com/shahzadmumtaz22/UoM_ClinicalCodes_Phenotypes_ForIeuan/tree/main/Extract2_MorePhenotypes) to add additional phenotypes. I have tested around 80 of them and they are available in this github subfolder. The remaining are around 30 and I will be testing them after 1pm today and hoping to get it tested before 2pm today. Once all will be uploaded all today, I will send an email to Ieuan to import into the HDR UK library. 

Regards,
Shahzad

**Comment by shahzadmumtaz22** [comment]
Hi Hannah, 

All the remaining 112 Phenotypes from the UoM are now available to import into HDR UK Phenotype library.

Regards,
Shahzad

**Comment by Hannah-Davies** [comment]
@ieuans the additional phenotypes are available to upload now
subdirectory ([https://github.com/shahzadmumtaz22/UoM_ClinicalCodes_Phenotypes_ForIeuan/tree/main/Extract2_MorePhenotypes](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshahzadmumtaz22%2FUoM_ClinicalCodes_Phenotypes_ForIeuan%2Ftree%2Fmain%2FExtract2_MorePhenotypes&data=04%7C01%7CH.K.Davies%40Swansea.ac.uk%7C8ce3257b639543919dfd08d9fc6564e3%7Cbbcab52e9fbe43d6a2f39f66c43df268%7C0%7C0%7C637818334682803459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RR44uN3nmq0zGKSau4%2FUVzTznw3NzCAAwfv8FRsDEMU%3D&reserved=0))
