### ISSUE TITLE
API: Tags are not included in results for Concepts or Working Sets

### ISSUE THREAD

**Issue by EtienneBadoche** [SwanseaUniversityMedical/concept-library#484]
[https://conceptlibrary.saildatabank.com/api/v1/concepts/](url) and [https://conceptlibrary.saildatabank.com/api/v1/workingsets/](url) don't include tags as part of the results. The tags are included on the detail endpoint, but this is inconsistent with phenotypes. Is this intended?

**Comment by elmessary** [comment]
done,

WS is about to be removed : old design

@EtienneBadoche please note to get the details of an entity you need call /detail/ endpoint which shows all data
e.g.
https://conceptlibrary.saildatabank.com/api/v1/concepts/C663/detail/
shows all data and code list
while
https://conceptlibrary.saildatabank.com/api/v1/concepts/C663/
shows basic info as search page does
