### ISSUE TITLE
API: Filtering concepts by tag has no effect.

### ISSUE THREAD

**Issue by EtienneBadoche** [SwanseaUniversityMedical/concept-library#486]
Using the tag_ids parameter for concepts in the API has no effect on the results.
With [https://conceptlibrary.saildatabank.com/api/v1/public/concepts/?tags_ids=23](url) the first concept returned has tag ids 20 and 18 but not 23.

**Comment by Hannah-Davies** [comment]
will be picked up with the upgrade

**Comment by elmessary** [comment]
@EtienneBadoche 
the query-string param is called tag_ids not tags_ids
which works fine.

https://conceptlibrary.saildatabank.com/api/v1/public/concepts/?tag_ids=23

no action required
