### ISSUE TITLE
Redesign -  Delete old boostrap theme style 

### ISSUE THREAD

**Issue by ZinnurovArtur** [SwanseaUniversityMedical/concept-library#490]
This theme style could be deleted because this style clashes with other styles and sometimes does not follow the original style.
(Could be integrated without issues to demo).

Examples:
Buttons new
<img width="709" alt="Screenshot 2021-11-16 141907" src="https://user-images.githubusercontent.com/25940388/142002443-36cdd491-1eac-4cc8-a7d5-fe4f342a077d.png">
Buttons old
<img width="677" alt="Screenshot 2021-11-16 141926" src="https://user-images.githubusercontent.com/25940388/142002449-4b73aff4-6d2d-48f5-9bea-badc159747e4.png">
Buttons in concept/phenotype old
<img width="623" alt="Screenshot 2021-11-16 142035" src="https://user-images.githubusercontent.com/25940388/142002728-8cc01f8e-1c39-4c16-831e-c200dc21c1ff.png">
Buttons in concept/phenotype new
<img width="553" alt="Screenshot 2021-11-16 142008" src="https://user-images.githubusercontent.com/25940388/142002691-98ccfd2b-8c78-4755-a357-2cd0fc3465bf.png">

**Comment by JackScanlon** [comment]
Closed by PR #809
