### ISSUE TITLE
place the phenotypes.healthdatagateway.org for API links in Phenotype/Concept detail page

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#493]
The API links in Phenotype/Concept detail page show the internal domain name 'http://web-phenotypes-hdr.chi.swan.ac.uk'
need to replace it by 'https://phenotypes.healthdatagateway.org ' in case of HDRUK brand.

for the rest: replace the ip  'http://192.168.20.157'
by 'https://conceptlibrary.saildatabank.com/'

**Comment by ChrisGreenSU** [comment]
Issue has now been resolved.
