### ISSUE TITLE
Import CSV files fails for some CSV formats from Excel (AR-1754)

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#553]
Moved over from JIRA: AR-1754

Fails from regular CSV format, succeeds with Microsoft CSV Ting Wang experienced issue.

Possibly due to handling of text delimiters.

**Comment by Hannah-Davies** [comment]
covered in #564

**Comment by JackScanlon** [comment]
Closed, no longer use same CSV method for file upload
