### ISSUE TITLE
CSV Handling - Delimiters (AR-3959)

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#564]
transferred over from JIRA: AP-3959

The CSV import function needs to be able to cater for:

a) Double quoted values - need to be treated as delimeters;

b) Comma delimiters;

c) Tab delimiters

**Comment by ChrisGreenSU** [comment]
Issue has now been resolved under pull request #576

**Comment by elmessary** [comment]
the  code works only for , ;
but not for \t |

perhaps adding delimiter dropdown list to the use for is a better solution,
since detecting delimiter automatically is tricky

**Comment by elmessary** [comment]
the  code works only for , ;
but not for \t |

perhaps adding delimiter dropdown list to the use for is a better solution,
since detecting delimiter automatically is tricky
