### ISSUE TITLE
Edit function - Expression select comp- add ability to select codes from components already in concept (ADP - AD-753)

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#566]
transferred from JIRA: AD-753

When building a component,  ADP would like to be able to add / remove codes by pulling in codes  which appear in a component that has already been added to the concept.

They would like to be able to either add codes in all the components already added or select a component from which to take the codes from.

**Comment by JackScanlon** [comment]
Linked with #1152, integrated into rule creation via Concept import
