### ISSUE TITLE
Link to documentation in footer is pointing to the incorrect information

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#581]

**Comment by Hannah-Davies** [comment]
How to submit a phenotype should point to the same page as the technical details in the About menu   https://conceptlibrary.demo.saildatabank.com/HDRUK/about/hdruk_about_technical_details/#technicaldoc

**Comment by ChrisGreenSU** [comment]
This has now been resolved with pull request #580 

The footer page now links to the contact-us page.

**Comment by elmessary** [comment]
fixed
