### ISSUE TITLE
Concept opens in a new Window

### ISSUE THREAD

**Issue by DSThayer** [SwanseaUniversityMedical/concept-library#589]
If you are on a phenotype and click on one of its concepts, the concept opens in a new window. Can this please be fixed so that it opens normally, in the same window. Generally, links to content within our own site should not be a new window. If there are any other cases of the same, can they also please be altered (or brought up for discussion if unsure what is correct).

I think this is quite good guidance on when to open links in a new window: https://stackoverflow.com/a/5602500/15363962

**Comment by elmessary** [comment]
Done
