### ISSUE TITLE
Inconsistent/confusing behavior - deleted concept

### ISSUE THREAD

**Issue by DSThayer** [SwanseaUniversityMedical/concept-library#594]
I'm not sure if this is just caused by data being messed around with for the demo site, but the concept C48 in the demo has inconsistent, confusing behavior.

It shows up (both when logged in and not logged in) like a normal concept. There is no indication that it has been deleted.

However, when you click on it you get a message at the top "this concept has been deleted", and it can't be edited.

I don't know whether it is just something wrong with this concept, or the general behavior for deleting is wrong. However, this ought to be corrected either way. (If it is just an issue with the data in the demo site, this concept can be removed entirely. I don't need it).

https://conceptlibrary.demo.saildatabank.com/concepts/C48/version/2272/detail/#home

**Comment by elmessary** [comment]
@DSThayer 
I think this is due demo data,
because some versions had child concepts which were deleted by api
I saw this before but thought I fixed it.

I'll delete it.

**Comment by elmessary** [comment]
done
