### ISSUE TITLE
amend the url / LDAP of the concept library within the gateway to enable all SerPs

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#602]
to open up the concept library to other Serps we want to remove some of the SAIL specific items, one being the reference to SAIL in the URL inside the gateway
Current link inside the gateway is [conceptlibrary.sail.ukserp.ac.uk](http://conceptlibrary.sail.ukserp.ac.uk)
needs to be [conceptlibrary.serp.ac.uk](http://conceptlibrary.serp.ac.uk)

**Comment by elmessary** [comment]
@ZinnurovArtur 
This needs to be done by IT after agreeing on the new url,
then we need to change any occurrence of this url in our code e.g. env var/allowed hosts/ docs/ R calling script, etc...

**Comment by elmessary** [comment]
the provided url is now
[conceptlibrary.serp.ac.uk](http://conceptlibrary.serp.ac.uk/)
