### ISSUE TITLE
BHF Data Science Centre phenotypes missing UUIDs

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#633]
@ieuans has been trying to load the new calibre phenotypes but they are missing UUIDS.

Can the UUIDS please be added the new phenotypes added and for any phenotypes added in the future

**Comment by spiros** [comment]
Good catch, thanks, I will add the UUIDs to them this week.
Just to clarify - these are not from CALIBER but from the BHF Data Science Centre.

**Comment by shahzadmumtaz22** [comment]
@spiros  Yes the ones from the BHF Data Science Centre have missing UUIDs.

**Comment by Hannah-Davies** [comment]
@spiros / @shahzadmumtaz22  any update on this please?

**Comment by spiros** [comment]
I've added UUIDs to the BHF COVID-IMPACT phenotypes which were missing - https://github.com/spiros/hdr-caliber-phenotype-library/commit/ca364e214cbc5dd9b9f36231c004114b5dd97c17
