### ISSUE TITLE
User Account Management

### ISSUE THREAD

**Issue by elmessary** [SwanseaUniversityMedical/concept-library#782]

**Comment by Hannah-Davies** [comment]
make some designs on how a user can create an account and the flow.
Users may also have an existing gateway account which could expire

**Comment by DSThayer** [comment]
Create a proposal for User Accounts ahead of August meeting (August 24th)

**Comment by JackScanlon** [comment]
- [x] Investigate UAM, SSO, and available Django-based solutions
- [x] Present proposal
- [ ] Awaiting meeting to progress

**Comment by JackScanlon** [comment]
Closed in favour of:
- #1108
