### ISSUE TITLE
Potential source of additional algorithms

### ISSUE THREAD

**Issue by spiros** [SwanseaUniversityMedical/concept-library#971]
Flagged in one of the HDR Slack channels, could we investigate how easy it would be to integrate phenotypes from here: 

https://www.phpc.cam.ac.uk/pcu/research/research-groups/crmh/cprd_cam/codelists/v11/

**Comment by Hannah-Davies** [comment]
@JackScanlon can you add a collection to these phenotypes please?

**Comment by JackScanlon** [comment]
Linked @ #979

**Comment by JackScanlon** [comment]
### Links generated with:
```python
min_phenotype_id = 1242
max_phenotype_id = 1287
for i in range(min_phenotype_id, max_phenotype_id + 1):
  print(f'https://conceptlibrary.demo.saildatabank.com/phenotypes/PH{i}/detail/')

```

### Links
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1242/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1243/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1244/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1245/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1246/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1247/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1248/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1249/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1250/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1251/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1252/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1253/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1254/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1255/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1256/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1257/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1258/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1259/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1260/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1261/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1262/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1263/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1264/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1265/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1266/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1267/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1268/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1269/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1270/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1271/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1272/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1273/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1274/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1275/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1276/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1277/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1278/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1279/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1280/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1281/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1282/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1283/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1284/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1285/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1286/detail/
https://conceptlibrary.demo.saildatabank.com/phenotypes/PH1287/detail/

**Comment by Hannah-Davies** [comment]
@spiros we have loaded the data to the Demo library - links above
Can you take a look and if everything ok we will load to production
